export { default as Header } from "./Header";
export { default as Intro } from "./Intro";
export { default as About } from "./About";
export { default as Classes } from "./Classes";
export { default as WhyChooseUs } from "./WhyChooseUs";
export { default as Features } from "./Features";
export { default as Testimonials } from "./Testimonials";
export { default as Contact } from "./Contact";
export { default as Footer } from "./Footer";
